services:

  database:
    build: ./Database
    container_name: database
    environment:
      POSTGRES_DB: gpsDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: 
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/db_postgres.sql:/docker-entrypoint-initdb.d/db_postgres.sql
    networks:
      - app-network

  kafka:
    build: ./kafka_2.13-3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - database
      - kafka
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: on-failure
    tty: true # je sais pas ce que ça fait mais askip ça aidera a debug


  test:
    build: ./producer_tests
    container_name: producer_tests
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    tty: true # je sais pas ce que ça fait mais askip ça aidera a debug


volumes:
  db_data:
  kafka_data:

networks:
  app-network:
    driver: bridge
